version: "3.9"
services:
  database:
    image: mysql/mysql-server:5.7
    restart: always
    container_name: chat-app-db
    environment:
      MYSQL_DATABASE: 'chat-app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - chat-db:/var/lib/mysql
    networks:
      - app-network

  chat-app:
    build: .
    ports:
      - '9000:9000'
    depends_on:
      - database
    environment:
      MYSQL_URL: mysql://root:password@tcp(database:3306)/chat-app?charset=utf8mb4&parseTime=True&loc=Local
    image: chat-app-service
    networks:
      - app-network

volumes:
  chat-db:

networks:
  app-network:
    driver: bridge